[UltraBlack]
; White on black background
text               = FFFFFF
subtext            = DEDEDE
nav-active-text    = 000000
main               = 000000
sidebar            = 000000
player             = 000000
card               = 000000
shadow             = 000000
main-secondary     = 292929
button             = 1DB954
button-secondary   = DEDEDE
button-active      = 1DB954
button-disabled    = 2f2f2f
nav-active         = DEDEDE
play-button        = DEDEDE
tab-active         = 292929
notification       = 292929
notification-error = 292929
playback-bar       = DEDEDE
misc               = FFFFFF
